# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Akademia Robotyki Lego - Robocamp Krosno  +48 515 777 883 
email: not_yet@email.com
description: >
    Akademia Robotyki Lego. Robocamp Krosno. 
logo: "/assets/images/robocamp_logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chineseantiquebuyers.github.io" # the base hostname & protocol for your site
paginate:	9 # The number of posts to show per page on your homepage
paginate_path: "/collectionN.:num/"

name: 'Robocamp Krosno'
bio: >
    Akademia Robotyki Lego. Robocamp Krosno 
author_image: "/assets/images/author.jpg"
twitter_username: robocampkrosno
github_username:  robocampkrosno

# Google Analytics
analytics_id: "UA-84736243-X"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

kramdown:
  parse_block_html: true

sass:
    sass_dir: css

plugins:
  - jekyll-paginate
  - jekyll-minifier

jekyll-minifier:
  exclude: 'atom.xml'
