# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chinese Antique Buyers +48 515 777 883 
email: not_yet@email.com
description: >
    Get FREE quote. Chinese Antique Buyers, We buy Asian antiques. 
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chineseantiquebuyers.github.io" # the base hostname & protocol for your site
paginate:	9 # The number of posts to show per page on your homepage
paginate_path: "/collectionN.:num/"

name: 'Chinese Antique Buyers'
bio: >
    chineseantiquebuyers.github.io, we buy Asian antiques. 
author_image: "/assets/images/author.jpg"
twitter_username: chineseantiquebuyers
github_username:  chineseantiquebuyers

# Google Analytics
analytics_id: "UA-84736243-X"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

kramdown:
  parse_block_html: true

sass:
    sass_dir: css

gems:
  - jekyll-paginate

theme: jekyll-theme-cayman